# Generated by Django 3.1.5 on 2021-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='email',
            new_name='std_email',
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
