# Generated by Django 3.1.5 on 2021-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_studentlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('place', models.CharField(max_length=25)),
            ],
        ),
    ]
